"""add ramos, ramo_docentes, ramo_alumnos

Revision ID: 3f97748787d0
Revises: 493f57c4b7b1
Create Date: 2026-07-10 18:11:59.784303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f97748787d0'
down_revision: Union[str, Sequence[str], None] = '493f57c4b7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ramos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ramos_codigo'), 'ramos', ['codigo'], unique=True)
    op.create_table('ramo_alumnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ramo_docentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ramo_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['ramo_id'], ['ramos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ramo_docentes')
    op.drop_table('ramo_alumnos')
    op.drop_index(op.f('ix_ramos_codigo'), table_name='ramos')
    op.drop_table('ramos')
    # ### end Alembic commands ###
