"""add cost tracking columns to entregas and mensajes_entrega

Revision ID: 493f57c4b7b1
Revises: ba4904848bea
Create Date: 2026-07-10 17:44:30.546346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493f57c4b7b1'
down_revision: Union[str, Sequence[str], None] = 'ba4904848bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregas', sa.Column('total_input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('entregas', sa.Column('total_output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('entregas', sa.Column('total_cached_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('entregas', sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False, server_default='0'))
    op.add_column('mensajes_entrega', sa.Column('model_usado', sa.String(length=50), nullable=True))
    op.add_column('mensajes_entrega', sa.Column('input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mensajes_entrega', sa.Column('output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mensajes_entrega', sa.Column('cached_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mensajes_entrega', sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes_entrega', 'cost_usd')
    op.drop_column('mensajes_entrega', 'cached_tokens')
    op.drop_column('mensajes_entrega', 'output_tokens')
    op.drop_column('mensajes_entrega', 'input_tokens')
    op.drop_column('mensajes_entrega', 'model_usado')
    op.drop_column('entregas', 'total_cost_usd')
    op.drop_column('entregas', 'total_cached_tokens')
    op.drop_column('entregas', 'total_output_tokens')
    op.drop_column('entregas', 'total_input_tokens')
    # ### end Alembic commands ###
